config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    root :to => "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:index,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :games, only: [:index,:new,:create,:show,:edit,:update,:destroy] do
      resources :reviews, only: [:show,:edit,:update,:destroy]
    end
  end

  scope module: :public do
    root :to => "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:show,:edit,:update]
    get 'users' => redirect("/users/sign_up")
    resources :games, only: [:index,:show] do
      resources :reviews, only: [:create,:edit,:update,:destroy]
    end
  end
  get "check" => "public/users#check"
  patch "withdrawal" => "public/users#withdrawal"
  get "search" => "public/searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :reviews, dependent: :destroy

  belongs_to :genre

  has_one_attached :image

  validates :name, presence: true, length: {maximum: 50}, uniqueness: true
  validates :explanation, presence: true

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  # scope :star_count, -> { joins(:reviews).order('reviews.star desc') }
  
  # 評価の高い順に並び替え
  def self.star_count
    averages = Game.all.map {|game| { id: game.id, ave: game.reviews.average(:star).to_f.round(1)}}
    sort_averages = averages.sort { |a, b| b[:ave] <=> a[:ave] }
    sort_ids = sort_averages.map { |ave| ave[:id] }
    Game.find(sort_ids).sort_by{ |o| sort_ids.index(o.id)}
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @game = Game.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @game = Game.where("name LIKE?","%#{word}%")
    else
      @game = Game.all
    end
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action:authenticate_admin!
  
  def new
    @game = Game.new
  end
  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:success] = "投稿しました。"
      redirect_to admin_game_path(@game.id)
    else
      flash[:danger] = "投稿に失敗しました。"
      redirect_to admin_games_path
    end
  end

  def index
    @games = Game.all
    @game = Game.new
  end

  def show
    @genres = Genre.all
    @game = Game.find(params[:id])
    @reviews = @game.reviews
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    game = Game.find(params[:id])
    if game.update(game_params)
      flash[:success] = "編集に成功しました"
      redirect_to admin_game_path(game)
    else
      flash[:danger] = "編集に失敗しました"
      render :edit
    end
  end

  def destroy
  end

  private

  def game_params
    params.require(:game).permit(:name,:explanation,:genre_id,:image)
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/views/admin/games/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h3 class="mt-5 text-center">ゲーム情報編集画面</h3>
      <%= flash[:danger] %>
      <%= form_with(model: @game, url: admin_game_path(@game), method: :patch) do |f| %>
        <div class="form-group">
          <%= f.label :name, "ゲームタイトル" %>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.label :genre, "ゲームジャンル" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "選択"} %>
        </div>
        <div class="form-group">
          <%= f.label :image, "画像" %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :explanation, "ゲーム概要" %>
          <%= f.text_area :explanation, rows: '3' %>
        </div>
        <div class="form-group">
          <%= f.submit "更新する", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/games/index.html.erb
<div class="container">
  <div class="row">
    <div class="col mx-auto">
      <!--フラッシュメッセージ-->
      <% if flash[:danger].present? %>
        <div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:danger] %>
        </div>
      <% end %>

      <h3 class="mt-5">登録ゲーム一覧・追加</h3>
      <% if @game.errors.any? %>
        <%= @game.errors.count %>件のエラーが発生しました
        <ul>
          <% @game.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with url: admin_games_path, model: @game do |f| %>
        <div class="form-group">
          <%= f.label :name, "ゲームタイトル", class: 'col-md-2' %>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.label :genre, "ジャンル", class: 'col-md-2' %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "選択"} %>
        </div>
        <div class="form-group">
          <%= f.label :image, "画像", class: 'col-md-2' %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :explanation, "ゲーム概要", class: 'col-md-2' %>
          <%= f.text_area :explanation, rows: '3' %>
        </div>
        <%= f.submit '登録', class:"btn btn-success col-md-2 ml-3" %>
      <% end %>


        <table class="table table-borderless">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>ジャンル</th>
              <th>概要</th>
              <th class="col-md-2"></th>
            </tr>
          </thead>
          <% @games.each do |game| %>
          <tbody>
            <tr>
              <td>
                <%= link_to admin_game_path(game.id) do %>
                  <%= game.name %>
                <% end %>
                </td>
              <td><%= game.genre.name %></td>
              <td><%= game.explanation %></td>
              <td class="col-md-2"><%= link_to '編集する', edit_admin_game_path(game), class: "btn btn-success" %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/admin/games/show.html.erb
<div class="container">
  <div class="row">

    <!--ジャンルリストの部分テンプレート-->
    <%= render "public/games/bygenre", genres: @genres %>
    <div class="col-md-8 mx-auto">
      <h2 class="mt-5 text-center"><%= @game.name %></h2>
      <div class="text-center">
        <% if @game.image.attached? %>
          <%= image_tag @game.image, class: "game_image" %>
        <% else %>
          <%= image_tag 'noimage', class: "game_image" %>
        <% end %>
      </div>

      <div class="mt-5 text-center">
        <h5>ジャンル：<%= @game.genre.name %></h5>
        <p><%= @game.explanation %></p>
        <div id="average_star_<%= @game.id %>"></div>
        <script>
          $(document).on('turbolinks:load', function() {
            let elem = document.querySelector('#average_star_<%= @game.id%>');
            if (elem == null) return;

            elem.innerHTML = ""
            let opt = {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              half: true,
              readOnly: true,
              score: <%= @game.reviews.average(:star).to_f.round(1) %>,
               //↑ 平均点を算出し、round関数で切り上げる
            };
            raty(elem, opt);
          });
        </script>
      </div>

      <div class="col-md-8 mt-5">
        <% if user_signed_in? %>
          <%= form_with model: [@game, @review] do |f| %>
            <div class="form-group">
              <%= f.label :title, "レビュータイトル" %><br>
              <%= f.text_field :title, placeholder: "タイトル", size: '30x10' %>
            </div>
            <div class="form-group">
              <%= f.label :comment, "レビューコメント" %>
              <%= f.text_area :comment, rows: '3',placeholder: "コメントを入力", size: '50x5' %><br>
            </div>
            <% if @review.id.nil? %>
              <div class="form-group" id="star">
                <%= f.label :star, "評価" %>
                <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
                <span id="post_raty"></span>
              </div>
              <script>
                $(document).on('turbolinks:load', function() {
                  let elem = document.querySelector('#post_raty');
                  if (elem == null) return;

                  elem.innerHTML = ""
                  let opt = {
                    starOn: "<%= asset_path('star-on.png') %>",
                    starOff: "<%= asset_path('star-off.png') %>",
                    starHalf: "<%= asset_path('star-half.png') %>",
                    scoreName: 'review[star]',
                  };
                  raty(elem, opt);
                });
              </script>
            <% end %>
            <div class="form-group">
              <%= f.submit "送信する", class: 'btn btn-primary' %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 mx-auto">
      <h4 class="p-3 border-bottom border-primary border-3">コメント一覧</h4>
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>投稿者名</th>
            <th>レビュータイトル</th>
            <th class="col-md-6">レビューコメント</th>
            <th>評価</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @game.reviews.each do |review| %>
          <tr>
            <div class="mt-5 text-center">
              <td><%= review.user.name %></td>
              <td><%= review.title %></td>
              <td><%= review.comment %></td>
              <td>
                <div id="star-rate<%= review.id %>"></div>
                <script>
                    $(document).on('turbolinks:load', function() {
                      let elem = document.querySelector('#star-rate<%= review.id %>');
                      if (elem == null) return;

                      elem.innerHTML = ""
                      let opt = {
                        starOn: "<%= asset_path('star-on.png') %>",
                        starOff: "<%= asset_path('star-off.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                        score: <%= review.star %>,
                        readOnly: true
                      };
                      raty(elem, opt);
                    });
                  </script>
                </td>
                <% if admin_signed_in? %>
                  <td>
                    <%= link_to admin_game_review_path(review.game, review), method: :delete, data: { confirm: "本当に削除してもよろしいですか？" } do %>
                      <button class="btn btn-danger">削除する</button>
                    <% end %>
                  </td>
                <% end %>
            </div>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>