config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    root :to => "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:index,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :games, only: [:index,:new,:create,:show,:edit,:update,:destroy] do
      resources :reviews, only: [:show,:edit,:update,:destroy]
    end
  end

  scope module: :public do
    root :to => "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:show,:edit,:update]
    get 'users' => redirect("/users/sign_up")
    resources :games, only: [:index,:show] do
      resources :reviews, only: [:create,:edit,:update,:destroy]
    end
  end
  get "check" => "public/users#check"
  patch "withdrawal" => "public/users#withdrawal"
  get "search" => "public/searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<!--フラッシュメッセージの部分テンプレート-->
<% flash.each do |key, message|%>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <%= message.html_safe %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My_Game</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a0900e118f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <div class="container">
          <a class="navbar-brand p-3 text-dark" href="/">
            <i class="fas fa-home"></i>
            MyGame
          </a>
          <%= render "public/searches/search" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-circle-exclamation"></i>概要
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to  user_path(current_user.id), class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-user"></i>マイページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to games_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-gamepad"></i>ゲーム一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-right-from-bracket"></i>ログアウト
                  <% end %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-circle-exclamation"></i>概要
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_users_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-user"></i>ユーザー一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-gamepad"></i>ジャンル一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_games_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-gamepad"></i>ゲーム一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-right-from-bracket"></i>ログアウト
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-circle-exclamation"></i>概要
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to games_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-gamepad"></i>ゲーム一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-user-plus"></i>新規登録
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-right-to-bracket"></i>ログイン
                  <% end %>
                </li>
                <li>
                  <%= link_to users_guest_sign_in_path, class: "nav-link text-dark", method: :post do %>
                    <i class="fa-solid fa-right-to-bracket"></i>ゲストログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <%= render "layouts/flash" %>
      <%= yield %>
    </main>

    <footer class="bg-info text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-8 mx-auto">
            <h6 class="text-dark text-center mt-2 mb-3">©My Game</h6>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/memo.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
    </div>
  </div>
</div>